linters:
  # linters to run in addition to default ones
  enable:
    - dupl
    - gofmt
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - godot
    - ifshort
    - gosec
    - misspell
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    #- wrapcheck # To think properly about it

# Get all linter issues, even if duplicated
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  #fix: true # we don’t want that for CI

linters-settings:
   # Forbid the usage of deprecated ioutil and debug prints
  forbidigo:
    forbid:
      - ioutil\.
      - ^print.*$
  staticcheck:
    # Should be better for it to be autodetected
    # https://github.com/golangci/golangci-lint/issues/2234
    go: "1.17"
