# This is for the CI. To run it, please use:
# golangci-lint run -c .golangci-ci.yaml.

# Please keep the list in sync with .golangci-ide.yaml. For rationale, see the other file.

linters:
  # linters to run in addition to default ones
  enable:
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - godot
    - gofmt
    - gosec
    - ifshort
    - misspell
    - revive
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    ##- wrapcheck # To think properly about it

# Get all linter issues, even if duplicated
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  #fix: true # we don’t want this in CI

linters-settings:
   # Forbid the usage of deprecated ioutil and debug prints
  forbidigo:
    forbid:
      - ioutil\.
      - ^print.*$
  staticcheck:
    # Should be better for it to be autodetected
    # https://github.com/golangci/golangci-lint/issues/2234
    go: "1.17"
