linters:
  # linters to run in addition to default ones
  enable:
    - dupl
    - gofmt
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forbidigo
# -E dupl -E gofmt  -E durationcheck -E errname -E errorlint -E exportloopref
# -E forbidigo -E forcetypeassert -E gci -E godot -E ifshort -E gosec -E makezero -E misspell
# -E thelper -E tparallel -E unconvert -E unparam -E wastedassign -E whitespace -E wrapcheck

# Get all linter issues, even if duplicated
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

linters-settings:
   # Forbid the usage of deprecated ioutil and debug prints
  forbidigo:
    forbid:
      - ioutil\.
      - ^print.*$
  staticcheck:
    # Should be better for it to be autodetected
    # https://github.com/golangci/golangci-lint/issues/2234
    go: "1.17"
