# This is for the IDE. We need to duplicate it because the --fast flag doesn’t filter manually enabled linters:
# https://github.com/golangci/golangci-lint/issues/1909.
# The idea was then to duplicate it, rename to -ide.yaml and reference this file in settings.json. That way, default
# manualy golangci-lint run would run all linters as CI. IDE will only run our fast list.
# However, we can’t use variables like ${workspaceRoot} in settings.json. https://github.com/microsoft/vscode/issues/2809.

# Please keep the list in sync.

linters:
  fast: true
  # linters to run in addition to default ones
  enable:
    - dupl
    #- durationcheck
    #- errname
    #- errorlint
    #- exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - godot
    - gofmt
    #- gosec
    - ifshort
    - misspell
    #- thelper
    #- tparallel
    #- unconvert
    #- unparam
    #- wastedassign
    #- whitespace
    ##- wrapcheck # To think properly about it

# Get all linter issues, even if duplicated
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true # we want this in IDE.

linters-settings:
   # Forbid the usage of deprecated ioutil and debug prints
  forbidigo:
    forbid:
      - ioutil\.
      - ^print.*$
  staticcheck:
    # Should be better for it to be autodetected
    # https://github.com/golangci/golangci-lint/issues/2234
    go: "1.17"
